### ISSUE TITLE
Pages Error

### ISSUE THREAD

**Issue by K-Twily** [XUOGROUP/ElementsOfHarmony#3]
**Describe the bug**
Not able to connect to our Pages in China, picture doesn’t load correctly also.
Is it because of the GFW?

**Smartphone:**
 - Device: iPad Air
 - OS: iOS 12
 - Browser: Safari

**Comment by K-Twily** [comment]
With VPN, I can connect, but considering most Chinese users don’t have VPN...

**Comment by Andy-K-Sparklight** [comment]
Got it. I already opened another: [https://cn.eoh.xuogroup.top](https://cn.eoh.xuogroup.top)
